services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "80:5000"
    volumes:
      - type: bind
        source: ./api
        target: /src
    environment:
      MONGO_URL: 'mongodb://mongo-api:27017/'
      PORT: 5000
    depends_on:
      - mongo-api

  mongo-api:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    build: grafana
    ports:
      - 3000:3000

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - 9093:9093

  mail:
    build:
      context: ./Mail
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./Mail
        target: /app

  rabbitMQ:
    image: rabbitmq:3.13-management
    restart: always
    ports: # TODO: remove port
      - 15672:15672

volumes:
  mongodata: {}
  prometheus-data: {}
