services:
  web:
    build:
#      context: ./week1
      dockerfile: Dockerfile.dev
    ports:
      - "80:5000"
    volumes:
      - type: bind
        source: ./week1
        target: /app
    environment:
      MONGO_URL: 'mongodb://mongo:27017/'
      PORT: 5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    build: grafana
    ports:
      - 3000:3000

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - 9093:9093
    env_file:
      - .env

volumes:
  mongodata: {}
  prometheus-data: {}
