global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "web"
    static_configs:
      - targets: ["web:5000"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"