services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:5000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      MONGO_URL: 'mongodb://mongo:27017/'
      PORT: 5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

volumes:
  mongodata: {}
  prometheus-data: {}
