services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      MONGO_URL: "mongo"
      DB_USERNAME: "mijn_mooie_gebruikersnaam"
      DB_PASSWORD: "mijn_mooie_wachtwoord"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mijn_mooie_gebruikersnaam #TODO: move to .env
      MONGO_INITDB_ROOT_PASSWORD: mijn_mooie_wachtwoord # TODO: move to .env
    volumes:
      - ../mongo-db-database-files:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mijn_mooie_gebruikersnaam
      ME_CONFIG_MONGODB_ADMINPASSWORD: mijn_mooie_wachtwoord
      ME_CONFIG_MONGODB_URL: mongodb://mijn_mooie_gebruikersnaam:mijn_mooie_wachtwoord@mongo:27017/ 
    depends_on:
      - mongo
