services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      MONGO_URL: 'mongodb://mongo:27017/'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mijn_mooie_gebruikersnaam
      ME_CONFIG_MONGODB_ADMINPASSWORD: mijn_mooie_wachtwoord
      ME_source_CONFIG_MONGODB_URL: 'mongodb://mongo:27017/'
    depends_on:
      - mongo

volumes:
  mongodata: {}
