services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      MONGO_URL: 'mongodb://mongo:27017/'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: {}
